version: '3'

vars:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD

dotenv:
  - api/.env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose up -d --build --remove-orphans {{.CLI_ARGS}}

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop all containers
    cmds:
      - docker compose stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose down -v --remove-orphans
